services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 10s
      timeout: 5s
      retries: 12

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"] # Note: Kibana 8+ prefers array format
      - xpack.security.enabled=false
      - xpack.security.authc.providers=[]
    ports:
      - "5601:5601"
    healthcheck:
      test: ["CMD-SHELL", "curl -s -I http://localhost:5601/api/status | grep -q 'HTTP/1.1 200 OK'"]
      interval: 10s
      timeout: 5s
      retries: 12

  my_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_server
    
    volumes:
      - ./log:/log:ro

    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
